"""Research-backed brand-page copy. Provenance: docs/CONTENT-SOURCES.md."""
from comap_applications import COMAP_APPLICATIONS

NORIS = 'https://www.noris-group.com'
COMAP = 'https://www.comap-control.com'
NS = NORIS + '/products-and-systems'
CC = COMAP + '/products/controllers'

BRANDS = {
    'noris': {
        'name': 'Noris', 'label': 'NORIS GROUP GmbH · INDONESIA',
        'title': 'Noris Instruments, Sensors & Marine Automation Indonesia | Araya Internusa',
        'description': 'Noris distributor in Indonesia: sensors, instruments, noriMos AMS, noriStar propulsion control and noriNet remote vessel monitoring with Araya Internusa.',
        'heading': 'Noris instruments,<br>sensors & automation.',
        'intro': 'From the measuring point to the control room. Explore Noris technology for your vessel, machinery, and industrial installation.',
        'image': 'noris-speed-sensors.webp', 'image_width': 768, 'image_height': 432,
        'alt': 'Noris flange and threaded speed sensors from the manufacturer portfolio',
        'image_caption': 'Speed sensors · Product image: Noris Group GmbH',
        'image_source': NS + '/sensors/speed-sensors/speed-sensor-portfolio',
        'profile_heading': 'Measurement expertise.<br>Marine system thinking.',
        'profile': 'Founded in Nuremberg in 1925, Noris grew from rotational-speed instrumentation into sensors, indication, signal processing, and maritime automation. The German group serves shipbuilding, railway, and machinery applications.',
        'local': 'PT Araya Internusa distributes Noris solutions in Indonesia. Discuss sensor and instrument replacement, alarm and monitoring requirements, or a wider control-system retrofit with our team.',
        'facts': [('Founded', '1925'), ('Origin', 'Nuremberg, Germany'), ('Focus', 'Measurement & automation')],
        'profile_source': NORIS + '/company/company-history',
        'portfolio_heading': 'Instruments, sensors<br>& marine systems.',
        'products': [
            {'id': 'speed-sensors', 'image': {'file': 'noris-speed-sensors.webp', 'width': 768, 'height': 432, 'alt': 'Noris threaded and flange-mounted rotational-speed sensors', 'caption': 'Speed-sensor portfolio'},
              'short': 'Speed sensors', 'title': 'Speed sensors', 'family': 'FAH13 · FAJ13 · Rotational-speed measurement',
             'body': 'Noris offers rotational-speed sensing for engines, gearboxes, and machinery. FAH13 and FAJ13 are examples in its speed-sensor portfolio; the correct version depends on the target and installation.',
             'application': 'RPM measurement and speed feedback for engine or machinery monitoring.',
             'selection': 'Target wheel, measuring gap, speed range, direction requirement, output signal, connector, and mounting dimensions.',
             'source': NS + '/sensors/speed-sensors/speed-sensor-portfolio'},
            {'id': 'temperature-sensors', 'image': {'file': 'noris-temperature-sensors.webp', 'width': 768, 'height': 512, 'alt': 'Noris temperature probes for marine measurement applications', 'caption': 'Marine temperature sensors'},
              'short': 'Temperature sensors', 'title': 'Temperature sensors', 'family': 'TA.81 / TA.82 · Pt100 / Pt1000 · Thermocouples',
             'body': 'The temperature portfolio includes resistance sensors, thermocouples, and thermistors in application-specific housings. TA.81 and TA.82 are screw-in examples with Pt100 or Pt1000 measuring elements.',
             'application': 'Temperature measurement on engines, machinery, and process equipment where the selected probe is suitable.',
             'selection': 'Temperature range, measuring element, insertion length, thread or flange, wiring arrangement, and process conditions.',
             'source': NS + '/sensors/temperature-sensors'},
            {'id': 'pressure-sensors', 'image': {'file': 'noris-pressure-sensor.webp', 'width': 768, 'height': 464, 'alt': 'Noris pressure transmitter with threaded process connection and electrical connector', 'caption': 'Pressure transmitter'},
              'short': 'Pressure sensors', 'title': 'Pressure sensors & transmitters', 'family': 'PAX9 · VD61',
             'body': 'Noris pressure transmitters convert pressure into a measurement signal for the wider system. The PAX9 family includes absolute and relative measurement variants; the manufacturer also lists VD61 transmitters.',
             'application': 'Pressure monitoring points in marine or industrial machinery, selected around the medium and operating range.',
             'selection': 'Absolute or gauge pressure, measuring range, medium compatibility, process connection, electrical output, and supply.',
             'source': NS + '/sensors/pressure-sensors'},
            {'id': 'instruments', 'image': {'file': 'noris-norimeter.webp', 'width': 768, 'height': 576, 'alt': 'Noris noriMeter NIQ3 square analogue RPM indicator', 'caption': 'noriMeter NIQ3 indicator'},
              'short': 'Instruments', 'title': 'Instruments & analogue indicators', 'family': 'noriMeter · NIR3 / NIQ3 · NIQ31 · SIR3 / SIQ3',
             'body': 'Noris indicators make speed, temperature, pressure, and position readable at the panel. noriMeter instruments use stepper motors; SIR3 and SIQ3 use moving-coil movements. Round and square formats suit different consoles.',
             'application': 'Local gauges, engine-room consoles, bridge indication, and instrument-panel replacement.',
             'selection': 'Input signal, display scale, panel cut-out, housing format, illumination, and any limit-switch functions.',
             'source': NS + '/analogue-indicators'},
            {'id': 'signal-processing', 'image': {'file': 'noris-signal-processing.webp', 'width': 768, 'height': 512, 'alt': 'Noris signal-processing modules and digital measurement display', 'caption': 'Signal-processing devices'},
              'short': 'Signal processing', 'title': 'Signal processing & limit monitoring', 'family': 'VF5 · VP5 / VPT5 · Measuring transducers',
             'body': 'Signal-processing devices connect a measuring point to indication or automation equipment. Noris examples include VF5 frequency transducers and VP5/VPT5 temperature transducers, alongside limit-monitoring devices.',
             'application': 'Measurement conversion and threshold signals for an existing monitoring or control installation.',
             'selection': 'Input and output types, supply voltage, isolation, switching thresholds, and the receiving equipment.',
             'source': NS + '/signal-processing'},
            {'id': 'alarm-monitoring', 'image': {'file': 'noris-norimos.webp', 'width': 768, 'height': 432, 'alt': 'Noris touchscreen displaying a noriMos machinery monitoring interface', 'caption': 'noriMos visualisation example'},
              'short': 'Alarm & monitoring', 'title': 'Marine alarm, monitoring & control', 'family': 'noriMos 4 · noriMos 3500 · IAMCS',
             'body': 'noriMos brings onboard alarms, operating data, visualisation, and control into an integrated system. Noris offers different architectures, from local data acquisition to larger vessel automation with several operating stations.',
             'application': 'Engine-room AMS, machinery monitoring, onboard alarm visibility, and monitoring-system retrofit.',
             'selection': 'Signal list and I/O count, operator stations, existing interfaces, redundancy, alarm philosophy, and vessel requirements.',
             'source': NS + '/maritime-system-solutions/alarm-monitoring-and-control'},
            {'id': 'propulsion-control', 'image': {'file': 'noris-noristar.webp', 'width': 768, 'height': 512, 'alt': 'Noris noriStar propulsion control lever and operating panel', 'caption': 'noriStar propulsion controls'},
              'short': 'Propulsion control', 'title': 'Propulsion remote control', 'family': 'noriStar · Bridge & local control stations',
             'body': 'noriStar coordinates propulsion components from the bridge and other control stations. Manufacturer applications include fixed- and controllable-pitch propellers, azimuth propulsion, waterjets, and bow or stern thrusters, with project-specific configuration.',
             'application': 'Propulsion-control and manoeuvring upgrades, including coordination of engines, gearboxes, and propellers.',
             'selection': 'Propulsion arrangement, control stations, engine/gearbox interfaces, feedback signals, interlocks, and vessel requirements.',
             'source': NS + '/maritime-system-solutions/propulsion-control'},
            {'id': 'norinet',
             'image': {'file': 'noris-norinet-display.webp', 'width': 768, 'height': 540, 'alt': 'Noris NORINET vessel performance dashboard displayed on a monitor', 'caption': 'noriNet performance visualisation example'},
             'short': 'noriNet remote monitoring', 'title': 'Remote monitoring & fleet performance',
             'family': 'noriNet / NORINET · Remote access & telemetry',
             'body': 'noriNet connects onboard machinery and navigation data to a cloud-based vessel or fleet view. Browser dashboards bring together operating trends, alarm history and reports; a separate VPN connection supports remote service access.',
             'application': 'Shore-side vessel monitoring, fleet comparison, remote diagnostics and performance analysis using available engine, position, fuel or energy measurements.',
             'selection': 'Existing AMS and engine systems, signal/protocol list, vessel count, internet connection, required reports, access roles and service scope.',
             'source': NS + '/maritime-system-solutions/remote-access-and-telemetry',
             'diagram': {'file': 'noris-norinet-system.webp', 'width': 1440, 'height': 960, 'alt': 'NORINET architecture: onboard AMCS, third-party systems and GPS connect to an interface unit; MQTT carries data to shore browsers, reports and REST API, with VPN remote support', 'caption': 'noriNet vessel-to-shore system structure'},
             'flow': ['Collect vessel data: AMCS, engine systems and navigation.', 'Connect through the onboard NORINET interface unit and vessel internet.', 'Send telemetry via MQTT to the cloud for browser views, reports and REST API integration.'],
             'diagram_note': 'Read from vessel to shore. NORICAN, Modbus and NMEA are interface examples shown by Noris; compatibility is reviewed for each installation. The dashed VPN path provides service access. Shore-side live visibility depends on connectivity and connected measurements.'},
        ],
        'applications': [
            ('Replace an instrument or sensor', 'Start with the existing part number and nameplate. Compare the electrical signal and mechanical fit before choosing a replacement.', 'instruments', 'Explore instruments'),
            ('Monitor machinery and onboard systems', 'Bring your signal list, alarm requirements, and console arrangement to a discussion about noriMos and the measurement chain.', 'alarm-monitoring', 'Explore noriMos'),
            ('Plan a propulsion-control retrofit', 'Describe the propulsion layout and operating stations so the control, feedback, and interlock requirements can be reviewed together.', 'propulsion-control', 'Explore noriStar'),
            ('See your vessel from shore', 'Review onboard data, internet access and reporting needs for a remote vessel or fleet overview. Bring the existing AMS and navigation interface details.', 'norinet', 'Explore noriNet'),
        ],
        'enquiry': [('Identify the equipment', 'Part number, nameplate photo, existing drawings, and the fault or intended change.'), ('Describe the measuring point', 'Range, medium, signal, connection, dimensions, and operating environment.'), ('Describe the system', 'I/O list, control stations, interfaces, alarm behaviour, and retrofit boundaries.'), ('Share the work location', 'Vessel or site, location in Indonesia, required quantity, and planned work window.')],
        'faqs': [
            ('Can a Noris sensor be replaced by a similar-looking model?', 'Physical appearance alone is insufficient. The measuring principle, range, output signal, supply, pin assignment, mounting, and environment must match the installation. Send the existing part number and drawings to Araya for a replacement discussion.'),
            ('What is the difference between noriMeter, noriMos, and noriStar?', 'noriMeter is an analogue indication family. noriMos is an integrated alarm, monitoring, and control system. noriStar handles propulsion remote control. They address different parts of the vessel’s measurement and automation requirements.'),
            ('How does noriNet relate to noriMos?', 'noriMos provides onboard alarm, monitoring and control. noriNet adds remote access and cloud-based visibility of connected vessel data. Share the existing system interfaces and connectivity with Araya to review an integration.'),
            ('How do I enquire about Noris products in Indonesia?', 'Contact PT Araya Internusa with the model or application, equipment photographs, quantity, and vessel or site location. Model availability, compatibility, documentation, and the agreed supply or service scope are confirmed for your enquiry.'),
        ],
        'marine_connection': 'Sensors, instruments, AMS, propulsion control, noriNet remote monitoring and system retrofit.',
        'industrial_connection': 'Machine measurement, process instruments, signal interfaces, and panels.',
        'other': 'comap', 'other_label': 'Explore ComAp engine & power control',
    },
    'comap': {
        'application_groups': COMAP_APPLICATIONS,
        'name': 'ComAp', 'label': 'COMAP CONTROL · INDONESIA',
        'title': 'ComAp Engine Control, Power Management & Load Sharing Indonesia | Araya Internusa',
        'description': 'Explore ComAp applications in Indonesia with Araya: marine engine and power control, standby and parallel generators, hybrid energy, battery storage, SCADA and fleet monitoring.',
        'heading': 'ComAp engine &<br>power control.',
        'intro': 'Start with your application. From marine propulsion and generator load sharing to standby power and hybrid energy, see how ComAp controls fit the complete system.',
        'image': 'comap-inteligen-500-g2.webp', 'image_width': 850, 'image_height': 592,
        'alt': 'ComAp InteliGen 500 G2 generator paralleling controller, manufacturer product image',
        'image_caption': 'InteliGen 500 G2 · Product image: ComAp',
        'image_source': CC + '/paralleling-gen-set-controllers/inteligen/inteligen-500-g2/',
        'profile_heading': 'Engine supervision.<br>Coordinated power.',
        'profile': 'Founded in Prague in 1991, ComAp develops control solutions for power generation and energy management. Its portfolio spans engine controllers, single and parallel generator control, marine power management, and monitoring software.',
        'local': 'PT Araya Internusa distributes ComAp solutions in Indonesia. Discuss engine control, automatic start/stop, generator synchronisation, load sharing, or a power-management retrofit with our team.',
        'facts': [('Founded', '1991'), ('Origin', 'Prague, Czech Republic'), ('Focus', 'Engine & power control')],
        'profile_source': COMAP + '/about/35-years-comap/',
        'portfolio_heading': 'From one engine<br>to coordinated power.',
        'products': [
            {'id': 'engine-control', 'image': {'file': 'comap-intelidrive-700-marine.webp', 'width': 768, 'height': 535, 'alt': 'ComAp InteliDrive 700 Marine engine controller with colour display', 'caption': 'InteliDrive 700 Marine'},
              'short': 'Engine control', 'title': 'Engine control & protection', 'family': 'InteliDrive · InteliDrive 700 Marine',
             'body': 'InteliDrive controllers supervise engine measurements, alarms, protection, and operating commands. InteliDrive 700 Marine is a manufacturer example for propulsion, auxiliary, emergency, and harbour engine applications.',
             'application': 'Marine engine supervision and engine-control retrofit with suitable protection and interfaces.',
             'selection': 'Engine ECU or conventional signals, RPM sources, I/O, operating stations, shutdown functions, and required documentation.',
             'source': CC + '/engine-controllers/intelidrive-700-marine/intelidrive-700-marine/'},
            {'id': 'generator-synchronisation', 'image': {'file': 'comap-inteligen-500-g2.webp', 'width': 850, 'height': 592, 'alt': 'ComAp InteliGen 500 G2 generator paralleling controller', 'caption': 'InteliGen 500 G2'},
              'short': 'Synchronisation & sharing', 'title': 'Generator synchronisation & load sharing', 'family': 'InteliGen · InteliGen 500 G2',
             'body': 'InteliGen 500 G2 controls diesel generator paralleling in grid-connected or island applications. It combines generator supervision with synchronisation, load/Var sharing, and power-management functions for suitable single or multiple-set arrangements.',
             'application': 'Parallel generators, automatic source operation, and sharing active and reactive demand between sets.',
             'selection': 'Generator ratings, governor and AVR interfaces, breakers, CT/VT data, operating modes, and compatibility with existing controllers.',
             'source': CC + '/paralleling-gen-set-controllers/inteligen/inteligen-500-g2/'},
            {'id': 'marine-power-management', 'image': {'file': 'comap-inteligen-1000-marine.webp', 'width': 768, 'height': 512, 'alt': 'ComAp InteliGen 1000 Marine controller module and terminal connections', 'caption': 'InteliGen 1000 Marine'},
              'short': 'Marine power management', 'title': 'Marine power management', 'family': 'InteliGen 1000 Marine · AC / DC applications',
             'body': 'InteliGen 1000 Marine manages onboard power sources and their cooperation. The manufacturer supports AC or DC arrangements under different software keys, including applications with generators, battery systems, or fuel cells.',
             'application': 'Vessel generating systems, load-dependent operation, and power-system retrofit discussions.',
             'selection': 'Single-line diagram, source types, bus arrangement, shore or bus-tie interfaces, load priorities, software keys, and vessel requirements.',
             'source': CC + '/generator-controllers/inteligen-1000-marine/'},
            {'id': 'single-generator', 'image': {'file': 'comap-intelilite-4-amf-25.webp', 'width': 768, 'height': 544, 'alt': 'ComAp InteliLite 4 AMF 25 single-generator controller', 'caption': 'InteliLite 4 AMF 25'},
              'short': 'Single generator & AMF', 'title': 'Single-generator & standby control', 'family': 'InteliLite · InteliLite 4 AMF 25',
             'body': 'InteliLite 4 AMF 25 is a single-generator controller for standby and prime-power applications. Its configuration options cover generator control and monitoring, with extension and communication options selected around the installation.',
             'application': 'Automatic mains-failure and start/stop discussions for a single generating set, without generator paralleling.',
             'selection': 'Mains sensing, engine interface, generator and breaker signals, transfer sequence, I/O needs, and extension modules.',
             'source': CC + '/single-gen-set-controllers/intelilite/intelilite-4-amf-25/'},
            {'id': 'local-monitoring', 'image': {'file': 'comap-inteliscada.webp', 'width': 768, 'height': 480, 'alt': 'ComAp InteliSCADA example screen showing generator measurements and controls', 'caption': 'InteliSCADA example screen'},
              'short': 'Local SCADA', 'title': 'Local monitoring & visualisation', 'family': 'InteliSCADA · PC monitoring',
             'body': 'InteliSCADA provides a PC-based monitoring environment for simple or advanced paralleling sites. It supports configurable visualisation and historical trends for a local view of the installation.',
             'application': 'Control-room displays, site supervision, and visibility of generator-system operating data.',
             'selection': 'Supported controller versions, communication network, signals, screens, user access, and software licensing requirements.',
             'source': COMAP + '/products/software-tools/monitoring-tools/pc-monitoring-tools/inteliscada/'},
            {'id': 'remote-monitoring', 'image': {'file': 'comap-websupervisor.webp', 'width': 768, 'height': 525, 'alt': 'ComAp WebSupervisor monitoring interface on desktop, tablet and phone', 'caption': 'WebSupervisor example screens'},
              'short': 'Remote monitoring', 'title': 'Remote monitoring & fleet visibility', 'family': 'WebSupervisor · Cloud-based monitoring',
             'body': 'WebSupervisor gives a remote view of connected ComAp and supported third-party devices. Its tools cover device status, alarm notification, data analysis, and fleet management, with features depending on connectivity and subscription.',
             'application': 'Monitoring generators across sites and reviewing operating information away from the installation.',
             'selection': 'Controller or gateway compatibility, internet access, account roles, data requirements, subscriptions, and remote-operation permissions.',
             'source': COMAP + '/products/software-tools/monitoring-tools/online-monitoring-tools/websupervisor/'},
        ],
        'applications': [
            ('One generator with automatic start/stop', 'Begin with the standby or prime-power sequence and the engine signals. A single-set application has different requirements from generator paralleling.', 'single-generator', 'Explore InteliLite'),
            ('Two or more generators in parallel', 'Review synchronisation, active/reactive load sharing, breaker control, and source priorities as one coordinated system.', 'generator-synchronisation', 'Explore InteliGen'),
            ('Marine engines and onboard power', 'Separate propulsion or auxiliary engine supervision from the vessel’s power-management requirements, then review their interfaces.', 'marine-power-management', 'Explore marine power control'),
        ],
        'enquiry': [('Identify the controller', 'Existing model, firmware if known, nameplate photo, and configuration backup if available.'), ('Describe the power system', 'Engine and generator ratings, number of sets, single-line diagram, breakers, governors, and AVRs.'), ('Explain the operating sequence', 'Start/stop logic, grid or island operation, load sharing, priorities, alarms, and the intended change.'), ('Share the project location', 'Vessel or site in Indonesia, operating constraints, required quantity, and planned shutdown window.')],
        'faqs': [
            ('What is the difference between engine control and generator power management?', 'Engine control supervises the engine, including measurements, commands, alarms, and protection. Generator power management coordinates electrical sources and their breakers, including synchronisation and load sharing where required. Some projects need both functions and a defined interface between them.'),
            ('Can I mix different ComAp controllers or replace an older model directly?', 'Compatibility is specific to the controller family, firmware, communication method, wiring, and operating sequence. A similar panel size does not establish compatibility. Share the existing models and configuration so a migration can be reviewed before hardware is selected.'),
            ('Does every ComAp controller include load sharing or remote monitoring?', 'No. Features vary between controller families, software options, extension modules, and communication arrangements. InteliLite single-set control, InteliGen paralleling, and WebSupervisor cloud monitoring address different requirements. Confirm the complete configuration, licensing, and connectivity for your project.'),
        ],
        'marine_connection': 'Engine supervision, generator synchronisation, automatic start/stop, and onboard power management.',
        'industrial_connection': 'Standby generation, parallel generators, load sharing, panels, and monitoring integration.',
        'other': 'noris', 'other_label': 'Explore Noris instruments & sensors',
    },
}
