"""Original application explanations based on ComAp's official application pages.

Research and scope limits: docs/COMAP-APPLICATIONS.md. These are manufacturer
application examples, not a record of Araya installations or stocked equipment.
"""
BASE = 'https://www.comap-control.com/application-areas/'


def diagram(file, height, caption, alt):
    return {'file': file, 'width': 900, 'height': height, 'caption': caption, 'alt': alt}


APPLICATION_DIAGRAMS = {
    'marine-ac-dc-pms': [
        diagram('comap-diagram-marine-dc.webp', 494, 'Marine DC / hybrid power example', 'ComAp example marine power arrangement connecting generator sources, conversion equipment, propulsion loads and shore supply'),
        diagram('comap-diagram-shore-connection.webp', 506, 'Shore connection example', 'ComAp marine shore-connection diagram highlighting the shore supply, controller and vessel bus'),
    ],
    'marine-engine-supervision': [diagram('comap-diagram-auxiliary-engine.webp', 506, 'Auxiliary engine control example', 'ComAp marine auxiliary-engine supervision example showing engine controllers and onboard system connections')],
    'marine-propulsion': [
        diagram('comap-diagram-mechanical-propulsion.webp', 311, 'Mechanical propulsion example', 'ComAp mechanical propulsion control diagram connecting bridge displays and engine controllers to two propulsion engines'),
        diagram('comap-diagram-electric-propulsion.webp', 329, 'Electric propulsion example', 'ComAp electric propulsion example with operator displays, controllers, variable-frequency drives and propulsion motors'),
    ],
    'prime-power': [diagram('comap-diagram-prime-power.webp', 682, 'Prime power with remote monitoring', 'ComAp prime-power example showing generating sets, controllers and communications to a remote site')],
    'hybrid-generation': [diagram('comap-diagram-off-grid-hybrid.webp', 496, 'Off-grid hybrid generation example', 'ComAp isolated hybrid microgrid diagram combining renewable generation, battery storage and generator sets to supply a village')],
    'chp-power': [diagram('comap-diagram-chp.webp', 636, 'Gas generation & CHP control example', 'ComAp CHP application diagram showing a gas-engine generator, controller, auxiliary process equipment and grid connection')],
    'fuel-cell-generation': [diagram('comap-diagram-fuel-cells.webp', 431, 'Multiple fuel cells with grid connection', 'ComAp fuel-cell application diagram with multiple controlled fuel-cell sources, grid supply and site load')],
    'battery-storage-control': [diagram('comap-diagram-bess.webp', 651, 'Grid-connected battery storage example', 'ComAp BESS diagram connecting battery racks, battery management, power conversion, auxiliaries and the site electrical system')],
}

COMAP_APPLICATIONS = [
    {
        'id': 'marine-applications', 'title': 'Marine',
        'intro': 'From the propulsion engine to the ship’s electrical bus. Define the engine, power sources, operating stations and vessel requirements together.',
        'flow': ['Engines, generators & shore power', 'Engine control & power management', 'Propulsion & onboard loads'],
        'diagram': {'file': 'comap-application-marine-pms.webp', 'width': 900, 'height': 506,
                    'alt': 'ComAp example marine AC power-management arrangement with generators, bus connections and shore supply',
                    'caption': 'Marine AC PMS example', 'source': BASE + 'marine/ac-dc-power-management/'},
        'items': [
            {'id': 'marine-ac-dc-pms', 'title': 'AC / DC power management',
             'summary': 'Coordinate generators, storage, shore supply and the electrical load.',
             'system': 'A vessel with several generators, bus sections and shore connection; DC or hybrid designs also include converters and battery storage.',
             'control': 'For AC systems: synchronisation, breaker sequencing, active/reactive load sharing and load-dependent start/stop. DC systems coordinate energy sources through conversion equipment. Emergency generation has its own defined operating arrangement.',
             'families': 'InteliGen 1000 Marine for source control; InteliMains 1010 Marine for shore, bus-tie and other breaker applications.',
             'review': 'Single-line diagram, AC/DC architecture, reserve power, heavy consumers, shore transfer and protection requirements.',
             'related': [('Marine PMS products', 'marine-power-management')],
             'source': BASE + 'marine/ac-dc-power-management/'},
            {'id': 'marine-engine-supervision', 'title': 'Engine control',
             'summary': 'Supervise propulsion, auxiliary, emergency and harbour engines.',
             'system': 'An engine with an electronic ECU or conventional sensors, local controls and remote operating displays.',
             'control': 'Read speed and engine measurements, manage start/stop commands, display alarms and execute configured protection. Auxiliary equipment such as pre-lubrication pumps can be included in the agreed sequence.',
             'families': 'InteliDrive marine controllers, including InteliDrive 700 Marine; suitable I/O, displays and protection equipment.',
             'review': 'Engine interfaces, signal list, local/remote authority, alarm and shutdown matrix, and operating stations.',
             'related': [('Engine-control products', 'engine-control')],
             'source': BASE + 'marine/engine-control/'},
            {'id': 'marine-emissions', 'title': 'Emissions reduction',
             'summary': 'Use operating data and coordinated energy sources to review fuel use.',
             'system': 'A conventional or hybrid vessel with engine measurements, fuel data and, where fitted, batteries or alternative-fuel equipment.',
             'control': 'Log operating data for comparison, coordinate hybrid power sources and support configured operating strategies. Specialist bi-fuel systems add dedicated fuel-control equipment; a standard controller alone does not convert an engine.',
             'families': 'Marine PMS, engine control, data logging and specialist bi-fuel solutions selected for the installation.',
             'review': 'Measured baseline, duty cycle, available signals, fuel system and the proposed operating strategy. Savings depend on the actual system.',
             'related': [('Marine power control', 'marine-power-management'), ('Remote monitoring', 'remote-monitoring')],
             'source': BASE + 'marine/emission-reduction/'},
            {'id': 'marine-propulsion', 'title': 'Propulsion control',
             'summary': 'Match mechanical or electric propulsion commands to the available machinery.',
             'system': 'A diesel-mechanical shaft line, or an electric propulsion motor driven by a variable-frequency drive on an AC or DC system.',
             'control': 'Mechanical applications supervise the propulsion engine and its operating interfaces. Electric applications coordinate drive speed demand with available power reserve and the vessel’s power-management system.',
             'families': 'InteliDrive 700 Marine for engine supervision; InteliMains 1010 Marine for electric propulsion control, with suitable marine displays and PMS interfaces.',
             'review': 'Propulsion layout, drive or gearbox interfaces, command stations, interlocks, feedback and required vessel documentation.',
             'related': [('Engine supervision', 'engine-control'), ('Marine PMS', 'marine-power-management')],
             'source': BASE + 'marine/propulsion-control/'},
        ],
    },
    {
        'id': 'power-generation-applications', 'title': 'Power generation',
        'intro': 'Start with the duty: standby during a mains failure, continuous site power, parallel generators or a specialist energy process.',
        'flow': ['Mains & generating sets', 'Start/stop, synchronisation & breakers', 'Site loads & operating priorities'],
        'diagram': {'file': 'comap-application-standby.webp', 'width': 900, 'height': 456,
                    'alt': 'ComAp example standby system connecting utility supply and a controlled generator to a building load',
                    'caption': 'Single-generator standby example', 'source': BASE + 'power-generation/standby/'},
        'items': [
            {'id': 'standby-power', 'title': 'Standby & automatic mains failure',
             'summary': 'Start a backup generator and transfer the load when mains power fails.',
             'system': 'One standby generator, mains sensing and interlocked source switching supplying a building or process.',
             'control': 'Detect a mains failure, start and supervise the engine, transfer to generator supply, then return to mains and stop after the configured recovery sequence. Remote visibility needs the appropriate communications hardware.',
             'families': 'InteliLite AMF controllers for single-set automatic mains failure; WebSupervisor for a connected fleet.',
             'review': 'Mains limits, transfer equipment, electrical/mechanical interlocks, start delays, return sequence and essential loads.',
             'related': [('Single-generator control', 'single-generator')],
             'source': BASE + 'power-generation/standby/'},
            {'id': 'prime-power', 'title': 'Prime power',
             'summary': 'Operate a generating set as the site’s main source of electricity.',
             'system': 'A single generating set serving a construction site, remote operation or other location without a dependable grid.',
             'control': 'Manual or remote starting, engine and generator supervision, protection and operating history. A multiple-set installation also needs a paralleling architecture when the sets share one electrical bus.',
             'families': 'InteliLite manual/remote-start or suitable single-set controllers; InteliGen for a separate paralleling requirement.',
             'review': 'Duty cycle, load steps, engine signals, site start demand and whether sets operate independently or in parallel.',
             'related': [('Single-set control', 'single-generator'), ('Paralleling & load sharing', 'generator-synchronisation')],
             'source': BASE + 'power-generation/prime-power/'},
            {'id': 'parallel-generation', 'title': 'Generator synchronisation & load sharing',
             'summary': 'Run two or more sets together and share the electrical demand.',
             'system': 'Multiple generators supplying a common bus, with optional mains connection and bus-tie breakers.',
             'control': 'Match the incoming generator before breaker closure, share active and reactive load, and start or stop sets around demand and configured reserve. Mains-parallel operation adds import/export and source-transfer requirements.',
             'families': 'InteliGen paralleling controllers, with suitable mains or tie-breaker control where required.',
             'review': 'Governor/AVR interfaces, CT/VT data, breaker feedback, load reserve, operating modes and existing controller compatibility.',
             'related': [('Synchronisation products', 'generator-synchronisation')],
             'source': 'https://www.comap-control.com/products/controllers/paralleling-gen-set-controllers/inteligen/inteligen-500-g2/'},
            {'id': 'hybrid-generation', 'title': 'Hybrid power generation',
             'summary': 'Combine generator sets with renewable generation and stored energy.',
             'system': 'Diesel generation, solar or other renewable sources and battery storage in a grid-connected or island installation.',
             'control': 'Balance generation and load, coordinate source setpoints and battery use, retain operating reserve and manage renewable output around system limits. Grid-connected designs also define permitted import and export.',
             'families': 'InteliNeo microgrid controllers with suitable generator, inverter and storage interfaces.',
             'review': 'Source ratings, inverter protocols, battery operating limits, grid/island modes and required reserve strategy.',
             'related': [('Generator paralleling', 'generator-synchronisation')],
             'source': BASE + 'power-generation/hybrid/'},
            {'id': 'mission-critical-power', 'title': 'Mission-critical power',
             'summary': 'Define backup control around essential loads and failure scenarios.',
             'system': 'Critical facilities such as hospitals or datacentres with multiple power sources and coordinated switchgear.',
             'control': 'Coordinate generator and breaker operation within an engineered backup scheme. The architecture must address source loss, maintenance states, communications failure and the loads that must remain supported.',
             'families': 'Application-specific generator, mains and bus-tie controllers; monitoring and redundancy chosen at system level.',
             'review': 'Required availability, permitted interruption, load priorities, failure cases and an agreed commissioning/test sequence.',
             'related': [('Paralleling controllers', 'generator-synchronisation'), ('Local monitoring', 'local-monitoring')],
             'source': BASE + 'power-generation/mission-critical/'},
            {'id': 'datacentre-power', 'title': 'Datacentres',
             'summary': 'Coordinate generating sets and switchgear with the facility power design.',
             'system': 'A datacentre with several generators, mains inputs and bus sections, coordinated with its wider backup infrastructure.',
             'control': 'Supervise generators, synchronisation and source/bus breakers. Suitable architectures add controller and communications redundancy, common visualisation and site-specific operating logic.',
             'families': 'InteliGen 1000 and InteliMains 1010 are manufacturer examples for demanding generator and mains/tie-breaker control.',
             'review': 'Electrical topology, redundancy targets, generator acceptance sequence, UPS interfaces and planned maintenance states. A controller alone does not establish a datacentre Tier rating.',
             'related': [('Paralleling functions', 'generator-synchronisation'), ('SCADA monitoring', 'local-monitoring')],
             'source': BASE + 'power-generation/mission-critical/datacenters/'},
            {'id': 'chp-power', 'title': 'Combined heat & power (CHP)',
             'summary': 'Coordinate electrical generation with useful heat recovery.',
             'system': 'A gas generating set with engine controls and a heat-recovery process, running alone or alongside the grid.',
             'control': 'Manage generator operation, engine ECU interfaces or specified engine-control functions, and auxiliary process logic. Heat recovery and electrical demand need a coordinated operating sequence.',
             'families': 'InteliSys Gas solutions with appropriate engine interfaces, process I/O and displays.',
             'review': 'Gas-engine model, ECU functions, fuel data, heat-demand sequence, process equipment and grid connection requirements.',
             'related': [('Local process visibility', 'local-monitoring')],
             'source': BASE + 'power-generation/chp/'},
            {'id': 'bifuel-hydrogen', 'title': 'Bi-fuel & hydrogen',
             'summary': 'Use specialist controls for a defined alternative-fuel engine project.',
             'system': 'A suitable diesel engine with an engineered gas or hydrogen supply and injection arrangement.',
             'control': 'Coordinate fuel substitution with engine speed, power and operating conditions using dedicated equipment. The project also requires an appropriate engine-protection and fuel-system design.',
             'families': 'InteliBifuel solutions and dedicated protection equipment, chosen for the engine and injection method.',
             'review': 'Engine suitability, fuel composition, injection method, protection, approvals and conversion scope. This requires more than changing a generator controller.',
             'related': [('Engine-control overview', 'engine-control')],
             'source': BASE + 'power-generation/bifuel-and-hydrogen/'},
            {'id': 'fuel-cell-generation', 'title': 'Fuel cells',
             'summary': 'Coordinate the electrical output of fuel-cell generating systems.',
             'system': 'A fuel-cell power package connected to other generating modules or the grid through suitable conversion equipment.',
             'control': 'Add electrical synchronisation, paralleling, load sharing and source-management functions where the package architecture supports them. Define how commands and measurements pass between the package and electrical controls.',
             'families': 'InteliGen-based electrical control is a manufacturer example; package-specific interfaces remain essential.',
             'review': 'Package controller, inverter/converter arrangement, AC/DC interfaces, grid/island operation and load-sharing strategy.',
             'related': [('Electrical paralleling', 'generator-synchronisation')],
             'source': BASE + 'power-generation/fuel-cells/'},
            {'id': 'rental-telecom-lighting', 'title': 'Rental, telecom & light towers',
             'summary': 'Control distributed power equipment and see its operating status.',
             'system': 'Rental generators, telecom-site power systems or light towers with local controls and, where required, a communications link.',
             'control': 'Apply the start/stop and monitoring arrangement suited to each asset. Fleet supervision can bring connected equipment status and operating records into one view for service planning.',
             'families': 'Single-set or application-specific controllers, with WebSupervisor for supported connected devices.',
             'review': 'Asset types, operating schedule, signals, network coverage, user access and required fleet reports.',
             'related': [('Single-set products', 'single-generator'), ('Fleet visibility', 'remote-monitoring')],
             'source': BASE + 'power-generation/rental-telecom-and-light-towers/'},
        ],
    },
    {
        'id': 'energy-management-applications', 'title': 'Smart energy management',
        'intro': 'Coordinate the whole energy system, then give operators the information they need. Energy management, battery control, SCADA and cloud monitoring have distinct roles.',
        'flow': ['Solar, batteries, generators & grid', 'Energy management & source controls', 'Site demand, dashboards & reports'],
        'diagram': {'file': 'comap-application-hybrid.webp', 'width': 900, 'height': 545,
                    'alt': 'ComAp example grid-connected hybrid microgrid integrating renewable generation, batteries, generators and site loads',
                    'caption': 'Grid-connected hybrid microgrid example', 'source': BASE + 'smart-energy-management/hybrid-energy-management/'},
        'items': [
            {'id': 'hybrid-energy-management', 'title': 'Hybrid energy management',
             'summary': 'Decide how the site’s available energy sources work together.',
             'system': 'An on-grid or isolated microgrid combining renewables, storage, generators and site demand.',
             'control': 'Coordinate source priorities, renewable limits, battery charging/discharging and generator dispatch. Operating strategy depends on whether the system is connected to the grid or must establish its own supply.',
             'families': 'InteliNeo microgrid control with compatible source controllers, meters and inverter interfaces.',
             'review': 'Energy priorities, storage capacity, reserve, import/export limits, transition requirements and source communications.',
             'related': [('Related hybrid generation application', 'hybrid-generation')],
             'source': BASE + 'smart-energy-management/hybrid-energy-management/'},
            {'id': 'battery-storage-control', 'title': 'Energy storage system control',
             'summary': 'Connect battery management, power conversion and auxiliary systems.',
             'system': 'A battery energy storage system (BESS) with a battery management system (BMS), power conversion system (PCS) and auxiliary equipment.',
             'control': 'Coordinate BMS and PCS data, charging/discharging commands, auxiliary monitoring and protection. Suitable arrangements add synchronising AC breaker control and integration with other microgrid assets.',
             'families': 'InteliNeo 530 BESS for storage-system control and interfaces to a higher-level energy manager.',
             'review': 'BMS/PCS compatibility, battery limits, breaker arrangement, auxiliary I/O and on-grid/off-grid operating requirements.',
             'related': [('Whole-site energy management', 'hybrid-energy-management')],
             'source': BASE + 'smart-energy-management/energy-storage-system-control/'},
            {'id': 'fleet-management-application', 'title': 'Fleet management',
             'summary': 'Review connected equipment across several sites from one platform.',
             'system': 'Distributed controllers and communications gateways sending operating information to a cloud account.',
             'control': 'WebSupervisor provides equipment status, alarm notifications, history and reporting. Account roles, communications and enabled features define access and any permitted remote actions.',
             'families': 'WebSupervisor with supported ComAp or third-party devices and suitable connectivity.',
             'review': 'Asset list, communications hardware, network access, subscriptions, alarm recipients, reports and user permissions.',
             'related': [('WebSupervisor products', 'remote-monitoring')],
             'source': BASE + 'smart-energy-management/fleet-management/'},
            {'id': 'scada-application', 'title': 'SCADA',
             'summary': 'Give site operators one view of measurements, alarms and trends.',
             'system': 'A local monitoring PC connected to controllers, meters and supported third-party devices.',
             'control': 'InteliSCADA brings measurements, alarm lists, historical trends and configured operating controls into a site-specific visualisation. Screen layout and available commands follow the connected equipment and access permissions.',
             'families': 'InteliSCADA with compatible controllers, communications and selected software functions.',
             'review': 'Signal list, network topology, required screens, trend storage, operator roles and allowed commands.',
             'related': [('InteliSCADA products', 'local-monitoring')],
             'source': BASE + 'smart-energy-management/scada/'},
            {'id': 'energy-market-integration', 'title': 'Energy market integration',
             'summary': 'Use supported market-price information as an operating input.',
             'system': 'A supported wholesale electricity market, a cloud dispatch service and compatible site controllers.',
             'control': 'Spot Price Dispatch compares market prices with configured thresholds and signals the site controller to adjust its operating strategy.',
             'families': 'ComAp Spot Price Dispatch with compatible controllers and market data access.',
             'review': 'ComAp currently lists this service for Australia and Singapore only. It is not presented here as an available Indonesian tariff service; confirm regional support before specifying it.',
             'related': [('Energy-management context', 'hybrid-energy-management')],
             'source': BASE + 'smart-energy-management/energy-market-integration/'},
        ],
    },
]

for group in COMAP_APPLICATIONS:
    for application in group['items']:
        application['diagrams'] = APPLICATION_DIAGRAMS.get(application['id'], [])
