"""Company content for the homepage and service pages.

Sources: the owner's live website (services, project-scope, clients, about and team pages)
and owner-supplied project scopes. See docs/CONTENT-SOURCES.md.
"""

CLIENTS = [
    {'name': 'PT PELNI (Persero)', 'logo': 'client-pelni.webp', 'width': 234, 'height': 90},
    {'name': 'Pelindo Jasa Maritim', 'logo': 'client-pelindo.webp', 'width': 294, 'height': 62},
    {'name': 'Pertamina', 'logo': 'client-pertamina.webp', 'width': 414, 'height': 96},
    {'name': 'TNI Angkatan Laut (Indonesian Navy)', 'logo': 'client-tni-al.webp', 'width': 85, 'height': 96},
    {'name': 'PT Armada Cakrawala Esa', 'logo': 'client-armada-cakrawala-esa.webp', 'width': 179, 'height': 53},
    {'name': 'PT USDA Seroja Jaya shipyard', 'logo': 'client-usda-seroja-jaya.webp', 'width': 392, 'height': 96},
]

STEPS = [
    ('Assess', 'We inspect the vessel or site, review drawings and nameplates, and find the root cause of the fault.'),
    ('Engineer', 'We define the scope, select compatible equipment and spares, and agree the schedule and shutdown window.'),
    ('Deliver', 'Our engineers repair, install or retrofit the system, then test and commission it with your team.'),
    ('Support', 'Handover documentation, a 6-month work guarantee and continued technical support after completion.'),
]

# label, service page, anchor on that page
CAPABILITIES = [
    ('Fire alarm & AMS', 'marine', 'alarms'),
    ('Engine safety devices', 'marine', 'safety'),
    ('Generator synchronisation', 'marine', 'generators'),
    ('Manoeuvring, CPP & bow thrusters', 'marine', 'propulsion'),
    ('Deck cranes', 'marine', 'cranes'),
    ('CNC & wire-cut machines', 'industrial', 'machinery'),
    ('Industrial cranes', 'industrial', 'cranes'),
    ('MV/LV generators', 'industrial', 'generators'),
    ('PLC, HMI & SCADA', 'automation', 'plc'),
    ('Switchboards & MCC', 'automation', 'panels'),
    ('Hazardous-area equipment', 'automation', 'hazardous'),
    ('Electronic card repair', 'automation', 'electronics'),
]

BRAND_GROUPS = [
    ('Automation & control', ['Siemens', 'ABB', 'Schneider Electric', 'Omron', 'Mitsubishi', 'Allen-Bradley', 'Honeywell', 'Modicon']),
    ('Marine systems', ['Consilium', 'Autronica', 'Tyco', 'MEDC', 'SIMOS', 'MaK', 'Janssen', 'Stein Sohn']),
    ('Power generation', ['Stamford', 'Leroy-Somer', 'Marathon', 'Caterpillar', 'SDMO', 'Denyo', 'GE']),
    ('Hazardous area', ['Stahl', 'Chalmit', 'Crouse-Hinds', 'CEAG', 'Glamox', 'Orga']),
    ('Machine tools', ['Fanuc', 'Okuma', 'Makino', 'Mori Seiki', 'Toshiba', 'Charmilles']),
]

SERVICES = {
    'marine': {
        'name': 'Marine', 'short': 'marine', 'label': 'Marine engineering',
        'title': 'Marine Electrical & Automation Services Indonesia | Araya',
        'description': 'Ship fire alarm and AMS, engine safety devices, generator synchronisation, CPP, bow thruster, deck crane and retrofit services across Indonesia.',
        'heading': 'Marine engineering.<br>Engine room to bridge.',
        'intro': 'Electrical, mechanical and automation work for passenger ships, cargo vessels, tugs and naval vessels, in port or during docking.',
        'hero_image': 'marine.webp', 'hero_width': 767, 'hero_height': 883, 'hero_alt': 'Araya technician inspecting marine engine equipment',
        'card_image': 'marine.webp', 'card_width': 767, 'card_height': 883, 'card_alt': 'Technical inspection of marine engine equipment',
        'summary': 'Electrical, mechanical and automation work on board, from engine room to bridge.',
        'highlights': ['Fire alarm, AMS & safety devices', 'Engine overhaul, control & synchronisation', 'Manoeuvring, CPP & bow thrusters', 'Deck cranes, AC & refrigeration'],
        'scope_heading': 'Systems we repair,<br>upgrade and retrofit.',
        'overview': 'A vessel fault often crosses machinery, electrical power and controls. We bring these together in one scope, from a failed sensor to a complete monitoring-system retrofit.',
        'groups': [
            ('alarms', 'Fire alarm, general alarm & AMS', 'Fire detection, general alarm and alarm-monitoring systems: fault finding, replacement of panels, detectors and displays, and full retrofit.'),
            ('safety', 'Engine safety devices', 'Safety, alarm and shutdown systems for main and auxiliary engines, including trip circuits, sensors and Sinpol-D safety devices.'),
            ('engines', 'Engine overhaul & control', 'Mechanical overhaul alongside engine monitoring, protection and control, including throttle and governor systems.'),
            ('generators', 'Generator synchronisation & PMS', 'Synchronisation, automatic start/stop, load sharing and power management for ship generators and switchboards.'),
            ('propulsion', 'Manoeuvring, CPP & bow thrusters', 'Bridge-to-engine manoeuvring systems, controllable-pitch propellers and bow thrusters, including control panels and feedback.'),
            ('navigation', 'Navigation & bridge equipment', 'Autopilot, gyro compass, steering systems and public address installations on the bridge and throughout the vessel.'),
            ('automation', 'Electrical panels, PLC & SCADA', 'Control and distribution panels, PLC logic, HMI operator screens and SCADA monitoring for onboard systems.'),
            ('monitoring', 'Tank level & cargo monitoring', 'Water-level, tank and cargo monitoring: sensors, signal conditioning, alarm thresholds and displays.'),
            ('cranes', 'Deck cranes & deck machinery', 'Mechanical, electrical and control work on deck cranes, winches and deck machinery, from fault finding to overhaul.'),
            ('hvac', 'AC & refrigeration systems', 'Air-conditioning and refrigeration plant on board, including electrical control, protection and fault diagnosis.'),
            ('retrofit', 'Retrofit of obsolete systems', 'Replacing obsolete or end-of-sale control equipment while keeping the machinery that still works, planned around your docking window.'),
            ('test-facilities', 'Hydrodynamic test facilities', 'Specialist design and engineering for marine research facilities, including ocean basins, towing tanks and hydrodynamics laboratories.'),
        ],
        'equipment': [
            ('Fire & alarm systems', ['Consilium', 'Autronica', 'Siemens', 'Tyco', 'Honeywell', 'MEDC', 'Hekatron']),
            ('Manoeuvring & propulsion', ['SIMOS', 'CAMOS', 'Stein Sohn', 'MaK', 'Janssen']),
            ('Monitoring & engine control', ['Noris', 'ComAp', 'Sinpol-D']),
            ('Generators', ['Stamford', 'Leroy-Somer', 'ABB', 'Marathon', 'GE']),
        ],
        'featured': [('noris', 'Speed, temperature and pressure sensors, indicators, noriMos AMS, noriStar propulsion control and noriNet remote monitoring.'),
                     ('comap', 'Marine engine controllers, generator synchronisation, load sharing and vessel power management.')],
        'enquiry': ['Vessel name, type and current location', 'Equipment make, model and nameplate photo', 'Fault symptoms, alarm messages or the change you need', 'Wiring diagrams or system drawings, if available', 'Planned docking or maintenance window'],
    },
    'industrial': {
        'name': 'Industrial', 'short': 'industrial', 'label': 'Industrial engineering',
        'title': 'Industrial Machinery, Crane & Generator Services | Araya',
        'description': 'Supply and repair of CNC, wire-cut and EDM machines, overhead and portal cranes, MV/LV generators and production machinery across Indonesia.',
        'heading': 'Industrial machinery.<br>Back in production.',
        'intro': 'Supply, repair and upgrade of machine tools, cranes, generators and production equipment for factories, ports and energy sites.',
        'hero_image': 'industrial.webp', 'hero_width': 767, 'hero_height': 883, 'hero_alt': 'Araya engineer working inside an industrial electrical cabinet',
        'card_image': 'industrial.webp', 'card_width': 767, 'card_height': 883, 'card_alt': 'Industrial electrical installation from Araya’s service photography',
        'summary': 'Supply and repair of production machinery, cranes and power equipment.',
        'highlights': ['CNC, wire-cut & EDM machines', 'Overhead, portal & luffing cranes', 'MV/LV generators', 'Casting, moulding & cutting machines'],
        'scope_heading': 'Machines and equipment<br>we supply and repair.',
        'overview': 'Industrial work starts with the machine and the process it serves. We combine mechanical repair with the electrical and control work that keeps it productive.',
        'groups': [
            ('machinery', 'CNC lathes & milling machines', 'Supply and repair of CNC lathes and milling machines, including controllers, servo drives and spindle systems.'),
            ('wirecut', 'Wire-cut & EDM machines', 'Wire-cut and EDM machine repair, from power supplies and control boards to mechanical alignment.'),
            ('cutting', 'NC gas & plasma cutting', 'NC gas-cutting and plasma-cutting machines, including PAC 500/600 plasma systems.'),
            ('production', 'Hobbing, casting & moulding', 'Hobbing machines, continuous-casting equipment and moulding machines: electrical, control and mechanical repair.'),
            ('cranes', 'Crane supply & repair', 'Level-luffing, slewing, overhead, portal and port cranes, including P&H cranes: mechanical, electrical and control systems.'),
            ('generators', 'MV/LV generators', 'Medium- and low-voltage generator supply, repair and control, including excitation, protection and synchronisation.'),
            ('electrical', 'Panels & motor controls', 'Electrical panels, MV/LV switchboards, motor-control centres, soft starters and variable-frequency drives.'),
            ('automation', 'PLC, HMI & instrumentation', 'Machine and process control, operator interfaces and instrument signals for new or existing production lines.'),
        ],
        'equipment': [
            ('CNC & machine tools', ['Fanuc', 'Mitsubishi', 'Toshiba', 'Mori Seiki', 'Okuma', 'Makino']),
            ('Wire-cut & EDM', ['Charmilles', 'Fuji Electric', 'Fanuc']),
            ('Casting & cranes', ['CEIA', 'P&H']),
            ('Generators', ['GE', 'Leroy-Somer', 'Stamford', 'ABB', 'Marathon']),
        ],
        'featured': [('comap', 'Standby, prime-power and parallel generator control, load sharing and remote monitoring for industrial sites.'),
                     ('noris', 'Speed, temperature and pressure measurement, indicators and signal processing for machinery.')],
        'enquiry': ['Site name and location', 'Machine or generator make, model and nameplate photo', 'Fault symptoms, error codes or the upgrade you need', 'Electrical drawings and PLC/HMI project files, if available', 'Required completion date or shutdown window'],
    },
    'automation': {
        'name': 'Automation & Electrical', 'short': 'automation', 'label': 'Automation & electrical',
        'title': 'PLC, SCADA & Electrical Panel Services Indonesia | Araya',
        'description': 'PLC and SCADA programming, switchboards and MCC, VFDs, hazardous-area equipment, protection relays and electronic card repair across Indonesia.',
        'heading': 'Automation &amp; electrical.<br>Control you can rely on.',
        'intro': 'Control, power distribution, instrumentation and electronics for vessels, plants and energy facilities, from design to commissioning.',
        'hero_image': 'control-room-1400.webp', 'hero_width': 1400, 'hero_height': 784, 'hero_variants': (('control-room-800.webp', 800), ('control-room-1400.webp', 1400)),
        'hero_alt': 'Marine control console with alarm panels and a Noris monitoring display',
        'card_image': 'control-room-1400.webp', 'card_width': 1400, 'card_height': 784, 'card_variants': (('control-room-800.webp', 800), ('control-room-1400.webp', 1400)),
        'card_alt': 'Marine control console with a Noris monitoring display',
        'summary': 'Control, power distribution and instrumentation for plants and vessels.',
        'highlights': ['PLC, HMI & SCADA', 'Switchboards, MCC & drives', 'Hazardous-area equipment', 'Protection relays & electronic cards'],
        'scope_heading': 'Control, power<br>and instrumentation.',
        'overview': 'From a single PLC to a complete switchboard, we design, supply, program and commission the electrical and control systems your operation depends on.',
        'groups': [
            ('plc', 'PLC programming & retrofit', 'PLC programming, troubleshooting and migration from obsolete platforms, with documented logic and I/O.'),
            ('scada', 'SCADA & HMI software', 'Operator screens, alarm handling, trends and supervisory control for plants and onboard systems.'),
            ('instrumentation', 'Process control & instrumentation', 'Regulators, transmitters, control valves, level valves and pressure safety valves for process plants.'),
            ('panels', 'Panels, switchboards & MCC', 'Electrical panels, MV/LV switchboards and motor-control centres, plus MV/LV power and instrument cable supply.'),
            ('drives', 'Soft starters & VFDs', 'Soft starters and variable-frequency drives for pumps, fans, conveyors and cranes, with parameter setup and commissioning.'),
            ('motors', 'Electric motors', 'Industrial and hazardous-area electric motors: supply, testing, installation and replacement.'),
            ('hazardous', 'Hazardous-area apparatus', 'Explosion-protected lighting, junction boxes, control stations and enclosures for oil, gas and chemical sites.'),
            ('protection', 'Electrical protection', 'Circuit breakers, fuses, thermal overload and earth-leakage relays, plus Sepam and MiCOM protection relays.'),
            ('power', 'Transformers, UPS & chargers', 'Distribution transformers, UPS systems and battery chargers for critical loads and control power.'),
            ('earthing', 'Surge protection, earthing & PFC', 'Lightning and surge protection, retractable earthing assemblies and reactive-power compensation.'),
            ('gensets', 'Generators & generating sets', 'MV/LV generators and complete generating sets: supply, control panels, synchronisation and load testing.'),
            ('electronics', 'Electronic card repair', 'Cloning and rebuilding circuit boards up to four layers; copying and programming EPROM, GAL, PAL, EPLD and PLCC ICs up to 64 pins.'),
        ],
        'equipment': [
            ('PLC & control', ['Siemens', 'ABB', 'Omron', 'Mitsubishi', 'Allen-Bradley', 'Modicon', 'Honeywell']),
            ('Switchgear & MCC', ['Schneider Electric', 'Siemens', 'GE', 'Areva']),
            ('Drives & soft starters', ['Schneider Electric', 'Rockwell Automation', 'Allen-Bradley', 'ABB']),
            ('Protection relays', ['Sepam 2000', 'Sepam 1000+', 'Areva MiCOM']),
            ('Hazardous area', ['Stahl', 'Chalmit', 'Crouse-Hinds', 'CEAG', 'Glamox', 'Orga']),
            ('Motors', ['Siemens', 'ABB', 'Reliance']),
            ('Transformers, UPS & chargers', ['Unindo', 'Trafindo', 'Saft', 'Gutor', 'GE', 'ICA']),
            ('Generating sets', ['SDMO', 'Denyo', 'Caterpillar', 'Stamford', 'Leroy-Somer']),
            ('Cables & surge protection', ['Jembo', 'Kabelmetal', 'Pirelli', 'Supreme', 'Critec', 'Erico']),
        ],
        'featured': [('comap', 'Engine and generator controllers, power management, InteliSCADA and WebSupervisor monitoring.'),
                     ('noris', 'Sensors, signal processing, limit monitoring and integrated alarm and monitoring systems.')],
        'enquiry': ['Site or vessel and its location', 'Single-line diagram, panel drawings or I/O list', 'PLC/HMI platform and existing program backup, if available', 'Fault description, alarm history or the new functions required', 'Hazardous-area classification, where relevant'],
    },
}
